version: '3.4'

services:
  catalogdb: 
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db

  basketredis:
    container_name: basketredis
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:DatabaseName=CatalogDb"
      - "DatabaseSettings:CollectionName=Products"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:Redis=basketcache:6379"
    depends_on:
      - basketredis
    ports:
      - "8001:80"

